### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by drallgood** [GjjvdBurg/HugoPhotoSwipe#22]
Hi.

I would like to define the sort order of images, since all my images have a caption that contains a number and I'd like to have them in order.
Right now it orders by file name, which would require me to rename all files.

Is there a way to configure this somehow?

**Comment by GjjvdBurg** [comment]
Hi there, thanks for checking out HugoPhotoSwipe!

For reasons I don't recall the photos were always sorted before writing out the yaml. By removing this the order of the photos in the yaml is maintained when writing out the markdown file for Hugo. This shouldn't affect current users because their photo order will be kept unchanged.

Please update your HugoPhotoSwipe installation to version 0.2.0, which includes this fix.

**Comment by drallgood** [comment]
Awesome. Thank you.

I've simply added the sorting to my build script
