### ISSUE TITLE
Dependency issue?

### ISSUE THREAD

**Issue by minilek** [GjjvdBurg/HugoPhotoSwipe#25]
Hi! First off, thanks a lot for this. I successfully installed HugoPhotoSwipe on my laptop, then successfully used it on a website I developed using Hugo.

I now tried to install on my desktop as per the wiki instructions and got this:

```
minilek@minilek:~$ pip install --process-dependency-links hugophotoswipe
Collecting hugophotoswipe
Collecting tzlocal (from hugophotoswipe)
Collecting tqdm (from hugophotoswipe)
  Using cached tqdm-4.19.6-py2.py3-none-any.whl
Requirement already satisfied: pytz in /usr/lib/python2.7/dist-packages (from hugophotoswipe)
Collecting smartcrop>=0.1 (from hugophotoswipe)
  Could not find a version that satisfies the requirement smartcrop>=0.1 (from hugophotoswipe) (from versions: )
No matching distribution found for smartcrop>=0.1 (from hugophotoswipe)
```

Do you know why this might be happening? (Warning: I'm a noob and this is probably not an issue with your package at all but is only related to my own incompetence.) I noticed hugophotoswipe depends on tqdm, so I tried installing that as well but also run into a problem:

```
minilek@minilek:~$ pip install tqdm
Collecting tqdm
  Using cached tqdm-4.19.6-py2.py3-none-any.whl
Installing collected packages: tqdm
Exception:
Traceback (most recent call last):
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/tqdm-4.19.6.dist-info'
```

**Comment by GjjvdBurg** [comment]
Hi there!

Thanks for checking out HugoPhotoSwipe!

These seem like different issues. The first one might be caused by an
outdated version of pip, but I'm not sure. Could you try updating pip and
seeing if the error persists? This can be done either with your package
manager or with pip itself.

For the second error, make sure you use ``sudo`` if you want to install the
package for your entire system or use the ``pip install --user tqdm``
command to install it just for you.

Hope this helps! Let me know if I can help further!

On 28 Feb 2018 19:05, "Jelani Nelson" <notifications@github.com> wrote:

Hi! First off, thanks a lot for this. I successfully installed
HugoPhotoSwipe on my laptop, then successfully used it on a website I
developed using Hugo.

I now tried to install on my desktop as per the wiki instructions and got
this:

minilek@minilek:~$ pip install --process-dependency-links hugophotoswipe
Collecting hugophotoswipe
Collecting tzlocal (from hugophotoswipe)
Collecting tqdm (from hugophotoswipe)
  Using cached tqdm-4.19.6-py2.py3-none-any.whl
Requirement already satisfied: pytz in
/usr/lib/python2.7/dist-packages (from hugophotoswipe)
Collecting smartcrop>=0.1 (from hugophotoswipe)
  Could not find a version that satisfies the requirement
smartcrop>=0.1 (from hugophotoswipe) (from versions: )
No matching distribution found for smartcrop>=0.1 (from hugophotoswipe)

Do you know why this might be happening? (Warning: I'm a noob and this is
probably not an issue with your package at all but is only related to my
own incompetence.) I noticed hugophotoswipe depends on tqdm, so I tried
installing that as well but also run into a problem:

minilek@minilek:~$ pip install tqdm
Collecting tqdm
  Using cached tqdm-4.19.6-py2.py3-none-any.whl
Installing collected packages: tqdm
Exception:
Traceback (most recent call last):
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/basecommand.py",
line 215, in main
    status = self.run(options, args)
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/commands/install.py",
line 342, in run
    prefix=options.prefix_path,
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/req/req_set.py",
line 784, in install
    **kwargs
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/req/req_install.py",
line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/req/req_install.py",
line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/wheel.py",
line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/wheel.py",
line 316, in clobber
    ensure_dir(destdir)
  File "/home/minilek/.local/lib/python2.7/site-packages/pip/utils/__init__.py",
line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied:
'/usr/local/lib/python2.7/dist-packages/tqdm-4.19.6.dist-info'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GjjvdBurg/HugoPhotoSwipe/issues/25>, or mute the thread

**Comment by minilek** [comment]
Thanks for the tips. I managed to install tqdm as you suggested, using ``pip install --user tqdm``.

As for upgrading pip to install hugophotoswipe, I'm still having no luck:

```
minilek@minilek:~$ pip install --upgrade pip
Requirement already up-to-date: pip in ./.local/lib/python2.7/site-packages
minilek@minilek:~$ pip --version
pip 9.0.1 from /home/minilek/.local/lib/python2.7/site-packages (python 2.7)
minilek@minilek:~$ pip install --process-dependency-links hugophotoswipe
Collecting hugophotoswipe
Collecting tzlocal (from hugophotoswipe)
Requirement already satisfied: tqdm in ./.local/lib/python2.7/site-packages (from hugophotoswipe)
Requirement already satisfied: pytz in /usr/lib/python2.7/dist-packages (from hugophotoswipe)
Collecting smartcrop>=0.1 (from hugophotoswipe)
  Could not find a version that satisfies the requirement smartcrop>=0.1 (from hugophotoswipe) (from versions: )
No matching distribution found for smartcrop>=0.1 (from hugophotoswipe)
```
I should note that my laptop, which did successfully complete ``pip install --process-dependency-links hugophotoswipe``, has the same version of pip (9.0.1).

**Comment by minilek** [comment]
Works now. Did:

``pip install --user --upgrade git+https://github.com/hhatto/smartcrop.py.git``
``pip install --user --process-dependency-links hugophotoswipe``

(the --user flag was important)

**Comment by GjjvdBurg** [comment]
@minilek Great that you've got it to work! I'll update the docs soon with this info, thanks for letting me know!
